# Generated by Django 5.0.1 on 2024-03-03 14:34

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('releaseDate', models.DateTimeField(default=datetime.datetime.now)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction'), ('Literature', 'Literature'), ('Sci-fi', 'Sci-fi'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy')], max_length=15)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=10)),
                ('summary', models.TextField(max_length=3000)),
                ('views', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=10)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction'), ('Literature', 'Literature'), ('Sci-fi', 'Sci-fi'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy')], max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('accountType', models.CharField(choices=[('Author', 'Author'), ('Reader', 'Reader')], max_length=10)),
                ('avatar', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
