# Generated by Django 5.0.1 on 2024-03-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fiction', models.CharField(default='Fiction', max_length=15)),
                ('NonFiction', models.CharField(default='Non-Fiction', max_length=15)),
                ('Literature', models.CharField(default='Literature', max_length=15)),
                ('SciFi', models.CharField(default='Sci-Fi', max_length=15)),
                ('Thriller', models.CharField(default='Thriller', max_length=15)),
                ('Fantasy', models.CharField(default='Fantasy', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.CharField(default='English', max_length=15)),
                ('Hindi', models.CharField(default='Hindi', max_length=15)),
                ('Sanskrit', models.CharField(default='Sanskrit', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='books.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(to='books.language'),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.ManyToManyField(to='books.genre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ManyToManyField(to='books.language'),
        ),
    ]
