# Generated by Django 5.0.1 on 2024-03-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_genre_fantasy_remove_genre_fiction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre1',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Literature', 'Literature'), ('Sci-Fi', 'Sci-Fi')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre2',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Literature', 'Literature'), ('Sci-Fi', 'Sci-Fi')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre3',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Literature', 'Literature'), ('Sci-Fi', 'Sci-Fi')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='language',
            name='language1',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='language',
            name='language2',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='language',
            name='language3',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Other', 'Other')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
